### ISSUE TITLE
[minor] users who like a track won't stay dancing after page refresh

### ISSUE THREAD

**Issue by jamesa** [stevenleeg/grooveboat#3]
Two scenarios I can think of:

1. 
* Room has two users, A and B
* A is dancing
* B refreshes
* A is no longer dancing

2.
* Room has two users, A and B
* A is dancing
* A refreshes
* A "leaves" the room and so rejoins as a different profile, no longer dancing (guessing)

I think the second scenario is probably fine/wontfix but the first scenario could be fixed.

**Comment by stevenleeg** [comment]
b465a49 fixes the first scenario but yeah I think the second is the desired behavior. tyty!!
